import "./globals.css";
import Nav from "./(components)/Nav";
import Provider from "./(components)/Provider";

export const metadata = {
  title: "Trade Logix",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="w-full h-screen max-h-screen flex flex-col justify-center items-center primary-bg-black">
        <Provider>
          <Nav />
          <div className="flex-grow text-default-text">{children}</div>
        </Provider>
      </body>
    </html>
  );
}
