import "./globals.css";
import Nav from "./(components)/Nav";
import Provider from "./(components)/Provider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="w-full h-screen max-h-screen flex flex-col justify-center items-center">
        <Provider>
          <Nav />
          <div className="flex-grow overflow-y-auto text-default-text">
            {children}
          </div>
        </Provider>
      </body>
    </html>
  );
}
